# **Numpy learning Notebook**

# Array Cration

In [ ]:
import numpy as np

In [ ]:
a = np.array([1 , 2 , 3])
print(a)

[1 2 3]


In [ ]:
a.shape

(3,)

In [ ]:
b = np.array([[1 , 2 , 3] , [4  , 5 , 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b.shape

(2, 3)

In [ ]:
c = np.zeros((2 , 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
c.shape

(2, 3)

In [ ]:
d = np.ones((2 , 3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
e = np.full((2 , 2) , 7)
print(e)

[[7 7]
 [7 7]]


In [ ]:
f = np.arange(0 , 10)
print(f)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
g = np.arange(0 , 10 , 2)
print(g)

[0 2 4 6 8]


In [ ]:
h = np.linspace(0 , 10 , 5)
print(h)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
i = np.random.rand(2 , 3)
print(i)

[[0.76605571 0.32392086 0.31493384]
 [0.24953683 0.72800508 0.30162588]]


In [ ]:
j = np.random.randint(1 , 10 , size = (2 , 4))
print(j)

[[3 8 2 2]
 [8 3 4 3]]


In [ ]:
k = np.array([1.5 , 2.5 , 3.5])
print(k.dtype) # -> float64

k = k.astype('int')
print(k)
print(k.dtype)

float64
[1 2 3]
int64


In [ ]:
l  = np.eye(4)
print(f'l:\n {l}')

l = np.eye(4 , k = 1)
print(f'\n new l: \n {l}')

l:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 new l: 
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
m = np.identity(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## exerice -> **Array Creation**

### Create an array containing numbers between 10 and 50 with a step of 5.




In [ ]:
arr = np.arange(10 , 50 , 5)

print(arr)

[10 15 20 25 30 35 40 45]


### Create a 3x3 array of 8.


In [ ]:
arr2 = np.full((3 , 3) , 8)

print(arr2)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


## Create a 5x5 array of random numbers between 0 and 100.

In [ ]:
arr3 = np.random.randint(0 , 100 , size=(5 , 5))
print(arr3)

[[70 34 33 73 70]
 [35  2 76 78 84]
 [93 86  7 35 99]
 [ 7 59  3 90 26]
 [51 98 67 22 74]]


In [ ]:
arr4 = np.random.rand(3 , ) * 10
print(arr4)
print(arr4.dtype) # -> float64

arr4 = arr4.astype('int64')
print(arr4)
print(arr4.dtype)

[0.85189034 3.64307765 5.20565708]
float64
[0 3 5]
int64


## Create a 4×4 matrix with only the value 1 on the main diagonal.


In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#  Indexing, Slicing, Shape Manipulation

In [ ]:
#1D array slicing
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])
print(a[1:4])
print(a[::2])

10
50
[20 30 40]
[10 30 50]


In [ ]:
#2d array
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(b[1,2])
print(b[1])
print(b[0:2 , 1:])

6
[4 5 6]
[[2 3]
 [5 6]]


### Copy vs View

In [ ]:
#View
c = np.array([1,2,3])
print(c)
d = c[0:2]
print(d)
d[0] = 999
print(f'c: \n {c}')
print(f'd: \n {d}')

[1 2 3]
[1 2]
c: 
 [999   2   3]
d: 
 [999   2]


In [ ]:
#Copy
e = np.array([1 , 2 , 3])
f = e[0:2].copy()
print(e)
print(f)
f[0] = 999
print(f'e:\n {e}')
print(f'f:\n {f}')


[1 2 3]
[1 2]
e:
 [1 2 3]
f:
 [999   2]


In [ ]:
#Masking
c = np.arange(12)
print(c)
print()
print('c[c>5] is:\n' ,c[c>5])
print()
mask = c > 10
print('c[mask] is\n' , c[mask])

[ 0  1  2  3  4  5  6  7  8  9 10 11]

c[c>5] is:
 [ 6  7  8  9 10 11]

c[mask] is
 [11]


In [ ]:
#Reshaping
d = np.arange(12)
print(f'd is \n{d}\n')
e = d.reshape(3 , 4)
print(f'e is \n{e}\n')
f = d.reshape(-1 , 6)
print(f'f is \n{f}\n')
g = d.reshape(4 , -1)
print(f'g is \n{g}\n')

d is 
[ 0  1  2  3  4  5  6  7  8  9 10 11]

e is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

f is 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

g is 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



In [ ]:
#Flatten vs Ravel
m = np.array([[1, 2], [3, 4]])
# print(m)
n = m.flatten()
# print(n)
n[0] = 999
# print(m)
# print(n)
o = m.ravel()
o[0] = 1000
# print(o)
# print(m)
m[0] = 123
# print(o)
# print(m)

In [ ]:
#Transpose
m = np.array([[1 , 2 ] , [3 , 4]])
print(m)
print(m.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


## exerice -> **Indexing , Slicing , Shape Manipulation**

### Create a 3x5 matrix from np.arange(1, 16)

In [ ]:
arr3 = np.arange(1 , 16)
print(arr3)
arr_new = arr3.reshape(3 , 5)
print()
print(arr_new)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Separate the second row and third column.



In [ ]:
arr_new[1,2]

np.int64(8)

### Extract all the even numbers from that matrix.

In [ ]:
arr_even = arr_new[arr_new % 2 == 0]
print(arr_even)

[ 2  4  6  8 10 12 14]


In [ ]:
arr_new = arr_new.reshape(1 , 15)
print(arr_new)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [ ]:
arr4 = np.eye(3)
print(arr4)
print()
arr5 = np.identity(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr_masked = arr_new[(arr_new > 10) & (arr_new % 3 == 0)]
print(arr_masked)

[12 15]


### Vectorization and Broadcasting

In [ ]:
#Vectorized code
A = np.array([1 , 2 , 3])
B = np.array([4 , 5 , 6])

print(A + B)

print('\n without numpy')
result = []
for i in range(len(A)):
  result.append(A[i]+B[i])

print(result)

[5 7 9]

 without numpy
[np.int64(5), np.int64(7), np.int64(9)]


In [ ]:
#Broadcasting
A = np.ones((3 , 3))
B = np.full((1 , 3) , 8)

A + B

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [ ]:
C = 10
A * C

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

## exerice -> **Vectorization and BroadCasting

### Create an array of shape (3, 4) and add a row of shape (1, 4)

In [ ]:
A = np.ones((3 , 4))
B = np.full((1 , 4) , 10)

print(A + B)

[[11. 11. 11. 11.]
 [11. 11. 11. 11.]
 [11. 11. 11. 11.]]


### Create a matrix of shape (4, 1) and add it with a 1x4 vector

In [ ]:
A = np.full((1 , 4) , 10)
B = np.full((4 , 1) , 20)

print(f'A \n {A}\n')
print(f'B \n {B}\n')
print(f'A + B:')
print(A + B)

A 
 [[10 10 10 10]]

B 
 [[20]
 [20]
 [20]
 [20]]

A + B:
[[30 30 30 30]
 [30 30 30 30]
 [30 30 30 30]
 [30 30 30 30]]


### By broadcasting, scale a 5x5 matrix so that each row is twice the size of the previous row


In [ ]:
A = np.array([[2] , [4] , [8] , [16] , [32]])
B = np.array([1 , 2 , 3 , 4 , 5])
print(A * B)

[[  2   4   6   8  10]
 [  4   8  12  16  20]
 [  8  16  24  32  40]
 [ 16  32  48  64  80]
 [ 32  64  96 128 160]]


### Create a random matrix and calculate the mean and z-score for each column

In [ ]:
A = np.random.randint(1 , 10 , size=(4 , 4) )
A_mean = np.mean(A , axis = 0)
A_std = np.std(A , axis = 0)

z = (A - A_mean) / A_std
print(z)

print()

np.where((z < 1) & (z > -1) , z , 0)



[[-0.33333333  0.63245553  0.81150267 -1.60356745]
 [-1.          1.26491106 -0.9918366   1.06904497]
 [ 1.66666667 -0.63245553 -0.9918366   0.        ]
 [-0.33333333 -1.26491106  1.17217053  0.53452248]]



array([[-0.33333333,  0.63245553,  0.81150267,  0.        ],
       [ 0.        ,  0.        , -0.9918366 ,  0.        ],
       [ 0.        , -0.63245553, -0.9918366 ,  0.        ],
       [-0.33333333,  0.        ,  0.        ,  0.53452248]])

## Matematical , Statistical and Logical Operation

In [ ]:
## Basic Matematical operation
a = np.array([1 , 2 , 3  , 4])
print(np.sum(a))
print(np.prod(a))
print(np.cumsum(a))
print(np.diff(a))
print(np.sqrt(a))
print(np.exp(a))

10
24
[ 1  3  6 10]
[1 1 1]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
## Statistical
b = np.array([[1, 2 , 3],[4 , 5, 6]])
print(np.mean(b))
print(np.var(b))
print(np.std(b))
print(np.min(b))
print(np.max(b))
print(np.argmin(b))
print(np.argmax(b))

3.5
2.9166666666666665
1.707825127659933
1
6
0
5


In [ ]:
##Logical
c = np.array([1 , 2 , 3 , 4 , 5])
print(np.all(c>0))
print(np.any(c>4))
print(np.all(c%2 == 0))


True
True
False


In [ ]:
np.min(b , axis = 1)

array([1, 4])

In [ ]:
np.max(b , axis = 1)

array([3, 6])

In [ ]:
np.any(b%2 == 0 , axis = 0)

array([ True,  True,  True])

## exerice -> **Operations**

### Create a 3x4 matrix with numbers between 1 and 50

In [ ]:
matrix = np.random.randint(1 , 50 , size = (3 , 4))
print(matrix)

[[26 26  4 30]
 [32 24 44  4]
 [ 8 49 24 19]]


### Calculate the sum, average, maximum and minimum for each row (axis=1)


In [ ]:
print(np.sum(matrix , axis = 1))

[ 86 104 100]


In [ ]:
print(np.mean(matrix , axis =1))

[21.5 26.  25. ]


In [ ]:
print(np.max(matrix , axis = 1))

[30 44 49]


In [ ]:
print(np.min(matrix , axis = 1))

[4 4 8]


### Check which columns contain a number greater than 30 (np.any)

In [ ]:
np.any(matrix > 30 , axis = 0)

array([ True,  True,  True, False])

### Check whether each row contains only even numbers? (np.all)

In [ ]:
np.all(matrix % 2== 0 , axis = 1)

array([ True,  True, False])

### Use cumsum to get the cumulative sum of each column


In [ ]:
np.cumsum(matrix, axis = 0)

array([[26, 26,  4, 30],
       [58, 50, 48, 34],
       [66, 99, 72, 53]])

### Use argmax to find the location of the largest value in each column

In [ ]:
np.argmax(matrix , axis = 0)

array([1, 2, 1, 0])

## Joining & Splitting Arrays

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6 ] , [7 , 8]])

np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6] , [7 , 8]])

np.concatenate((a , b) , axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
x = np.array([1, 2])
y = np.array([3, 4])


print(np.vstack((x, y)))


print(np.hstack((y , x)))

[[1 2]
 [3 4]]
[3 4 1 2]


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])


print(np.stack((a , b) , axis = 1))

print(np.stack((a , b) , axis  = 0))

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


In [ ]:
z = np.array([10, 20, 30, 40, 50, 60, 70])

print(np.split(z , 7))
print(np.array_split(z , 4))

[array([10]), array([20]), array([30]), array([40]), array([50]), array([60]), array([70])]
[array([10, 20]), array([30, 40]), array([50, 60]), array([70])]


In [ ]:
a = np.array([1, 2])

print(np.tile(a , 4))
print(np.repeat(a , 4))

[1 2 1 2 1 2 1 2]
[1 1 1 1 2 2 2 2]


In [ ]:
a = np.arange(4)
print(a)
print()
result = np.tile(a, (3, 2))
print(result)

[0 1 2 3]

[[0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]]


In [ ]:
a = np.arange(4)
# result = np.repeat(a[np.newaxis, :], 3, axis=0)
# print(result)
np.repeat(a[np.newaxis, :] , 3 , axis = 0)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.tile(np.arange(5) ,(4 , 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
np.tile(np.arange(5) ,(5 , 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
np.tile(np.arange(4)[:, np.newaxis], (5,1))

array([[0],
       [1],
       [2],
       [3],
       [0],
       [1],
       [2],
       [3],
       [0],
       [1],
       [2],
       [3],
       [0],
       [1],
       [2],
       [3],
       [0],
       [1],
       [2],
       [3]])

In [ ]:
np.arange(4).shape

(4,)

In [ ]:
np.arange(4)[: , np.newaxis].shape

(4, 1)

In [ ]:
np.tile(np.arange(4)[: , np.newaxis] , 4)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [ ]:
np.tile(np.arange(5) , (4 , 1) )

TypeError: tile() got an unexpected keyword argument 'axis'

In [ ]:
np.tile(np.arange(5) , (4 , 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
a= np.array([1, 2 , 3 ,4, 5, 6 ,7 , 8])
np.where(a>5 , a  , -1)

array([-1, -1, -1, -1, -1,  6,  7,  8])

In [ ]:
a = np.array([0, 1, 2])
np.tile(a, (2 , 1))

array([[0, 1, 2],
       [0, 1, 2]])

In [ ]:
b = np.array([5 , 6])
np.repeat(b , 2)

array([5, 5, 6, 6])

In [ ]:
a = np.array([1, 2, 3])
np.repeat(a[: , np.newaxis] , 2 , axis = 1)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
x = np.array([10, 20, 30])


x[np.newaxis , :]

array([[10, 20, 30]])

In [ ]:
x[:  , np.newaxis]

array([[10],
       [20],
       [30]])

In [ ]:
a = np.array([1, 2, 3])


np.repeat(a[: , np.newaxis] , 2 , axis = 1)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
a = np.array([1, 2, 3])
b = a[np.newaxis , :]

In [ ]:
c = a[: , np.newaxis]
print(c)

[[1]
 [2]
 [3]]


In [ ]:
b*c

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

## Sorting and Searching

In [ ]:
a = np.array([[8, 3, 1], [4, 9, 2]])
print(a)
print()
print(np.sort(a))
print()
print(np.sort(a , axis = 0))
print()
print(np.sort(a , axis = 1))

[[8 3 1]
 [4 9 2]]

[[1 3 8]
 [2 4 9]]

[[4 3 1]
 [8 9 2]]

[[1 3 8]
 [2 4 9]]


In [ ]:
a = np.array([40, 10, 30, 20])
y =  np.argsort(a)
print(y)
x = np.array([a[i] for i in np.argsort(a)])
print(x)

[1 3 2 0]
[10 20 30 40]


In [ ]:
a[np.argsort(a)]

array([10, 20, 30, 40])

In [ ]:
a = np.array([12, 7, 5, 20, 4, 13])
print(np.where(a > 10))
a[np.where(a>10)]

(array([0, 3, 5]),)


array([12, 20, 13])

In [ ]:
a = np.array([0, 3, 0, 7, 0, 1])
np.nonzero(a)

(array([1, 3, 5]),)

In [ ]:
a = np.array([[2, 4, 0],
              [0, 5, 3]])

np.argwhere(a > 2)

array([[0, 1],
       [1, 1],
       [1, 2]])

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 4])

np.in1d(a , b)

/tmp/ipython-input-28-2594992298.py:4: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a , b)


array([False,  True, False,  True, False])

In [ ]:
a = np.array([1, 2, 2, 3, 3, 3, 4])

np.unique(a , return_counts= True)

(array([1, 2, 3, 4]), array([1, 2, 3, 1]))

In [ ]:
a.size

7

In [ ]:
a.itemsize

8

In [ ]:
a =np.array( [1 , 2 ,3 , 4 , 5, 6])
a[ [1 , 2 , 5] ]

array([2, 3, 6])

In [ ]:
print(b)
b.shape

[2 4]


(2,)

In [ ]:
a = np.array([[1 , 2 , 3 , 4], [5 , 6 , 7 , 8]])
a.shape

(2, 4)

In [ ]:
b = b[: , np.newaxis]
b

array([[[2]],

       [[4]]])

In [ ]:
a+b

array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12]])

In [ ]:
sales = np.array([120, 80, 95, 60, 150, 200, 110])
months = np.array(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"])

sorted = np.where(sales < 100)
sort_bottom_to_head = np.sort(months[ sorted ] )
sort_bottom_to_head[::-1]

array(['Mar', 'Feb', 'Apr'], dtype='<U3')

In [ ]:
sales = np.array([120, 80, 95, 60, 150, 200, 110])
months = np.array(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"])


filtered_sales = sales[sales<100]
print(filtered_sales)
filtered_months = months[sales<100]
print(filtered_months)
idx = np.argsort(filtered_sales)
print(idx)
result = filtered_months[idx]
print(result)

[80 95 60]
['Feb' 'Mar' 'Apr']
[2 0 1]
['Apr' 'Feb' 'Mar']


In [ ]:
array = np.random.randint(10 , 99 , size=(6 , 6))
array_mean = np.mean(array)
print(array)
result = array[(array > array_mean) & (array % 2 == 0)]
print(result)

[[58 76 14 18 52 54]
 [23 37 87 42 37 98]
 [74 24 24 54 33 51]
 [49 16 28 13 14 83]
 [72 15 10 87 94 62]
 [17 91 98 57 68 24]]
[58 76 52 54 98 74 54 72 94 62 98 68]


In [ ]:
array = np.array([1 , 2 , 3, 4])
array1 = array[: , np.newaxis]
array2 = array[np.newaxis , :]
print(array1)
print(array2)
print(array1 * array2)

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
array = np.random.randint(1 , 100 , 10)
print(array)
sorted_array = np.sort(array)
print(sorted_array)
argsorted_array = np.argsort(array)
print(argsorted_array)
array[np.argsort(array)]

[31 69 58 39 96 88 36 42 35 81]
[31 35 36 39 42 58 69 81 88 96]
[0 8 6 3 7 2 1 9 5 4]


array([31, 35, 36, 39, 42, 58, 69, 81, 88, 96])

In [ ]:
array = np.random.randint(0, 10 , 12)
print(array)
array[array == 0] = 100
print(array)
np.where(array == 0 , 100 , array)

[0 3 5 4 2 2 1 2 6 9 5 4]
[100   3   5   4   2   2   1   2   6   9   5   4]


array([100,   3,   5,   4,   2,   2,   1,   2,   6,   9,   5,   4])

In [ ]:
array = np.random.randint(1 , 20 , size = (6 , 4))
print(array)
sum_each_row = np.sum(array , axis = 1)
mean_each_column = np.mean(array , axis = 0)
print(sum_each_row)
idx=np.argmin(sum_each_row)
array_min= array[idx , :]
print(mean_each_column)

[[12  2 13  5]
 [ 2 12 16 16]
 [ 4 19  5 15]
 [ 8 11 13  7]
 [17 16 16 12]
 [10  7 10  3]]
[32 46 43 39 61 30]
[ 8.83333333 11.16666667 12.16666667  9.66666667]


In [ ]:
scores = np.random.randint(0 , 20 , size = (5 , 6))
print('scores:\n' , scores)
mean_each_student = np.mean(scores , axis = 1)
print('each student average in 6 lesson : \n' , mean_each_student)
highest_mean_student_idx = np.argmax(mean_each_student)
highest_mean_student = scores[highest_mean_student_idx , :]
print("highest mean student scores : \n" , highest_mean_student)
# -------------------------
print()
mean_each_lesson= np.mean(scores , axis = 0 )
print('each lesson average from 5 student : \n' , mean_each_lesson)
lowest_mean_lesson_idx = np.argmin(mean_each_lesson)
lowest_mean_lesson = scores[: , lowest_mean_lesson_idx]
print('lowest mean lesson scores: \n' , lowest_mean_lesson)
# --------------------------
print()
scores_under_10 = scores[scores < 10]
print(scores_under_10)
number_of_scores_under_10 = len(scores_under_10)
number_of_total = len(scores.flatten())
print('number of scores under 10:\n' , number_of_scores_under_10)
print('number of all scores: \n' , number_of_total)
scale_of_under_ten =( number_of_scores_under_10 / number_of_total)*100
print(f'scale of under ten scores: \n {scale_of_under_ten:.2f} %')

scores:
 [[12 15  5 11  8  2]
 [ 6 17  5  7 10 19]
 [ 5  9 15 18  8 19]
 [ 8 13  0  6  6 16]
 [19  4  8  0 10  5]]
each student average in 6 lesson : 
 [ 8.83333333 10.66666667 12.33333333  8.16666667  7.66666667]
highest mean student scores : 
 [ 5  9 15 18  8 19]

each lesson average from 5 student : 
 [10.  11.6  6.6  8.4  8.4 12.2]
lowest mean lesson scores: 
 [ 5  5 15  0  8]

[5 8 2 6 5 7 5 9 8 8 0 6 6 4 8 0 5]
number of scores under 10:
 17
number of all scores: 
 30
scale of under ten scores: 
 56.67 %


In [127]:
scores = np.random.randint(0 , 20 , size = (8 , 5))
print(scores)
mean_studens = np.mean(scores , axis = 1)
print(np.mean(scores , axis = 1))
print(np.sum(scores < 10 , axis = 1))
idx = np.where(np.sum(scores < 10 , axis = 1) >= 2)
print(idx)
scores[idx , :]


[[11 14 11 19 18]
 [ 1  9  6 15 14]
 [ 0 16  0 18 18]
 [ 6 10 13  9  1]
 [ 9 16  4  4 11]
 [14  3 15  5  2]
 [ 1 19  1 13 15]
 [13 17 13  1  4]]
[14.6  9.  10.4  7.8  8.8  7.8  9.8  9.6]
[0 3 2 3 3 3 2 2]
(array([1, 2, 3, 4, 5, 6, 7]),)


array([[[ 1,  9,  6, 15, 14],
        [ 0, 16,  0, 18, 18],
        [ 6, 10, 13,  9,  1],
        [ 9, 16,  4,  4, 11],
        [14,  3, 15,  5,  2],
        [ 1, 19,  1, 13, 15],
        [13, 17, 13,  1,  4]]])